### ISSUE TITLE
Практика «Скользящее среднее»

### ISSUE THREAD

**Issue by KillWolfVlad** [KillWolfVlad/ulearn-cheats#1]
* Ошибка в [master](https://github.com/KillWolfVlad/ulearn-cheats/blob/master/2/2/Smooth.exercise/MovingAverageTask.cs) ветке [хз правильно ли, но долго]

```
Time limit exceeded
```

* Ошибка в [develop-yield-avg](https://github.com/KillWolfVlad/ulearn-cheats/blob/develop-yield-avg/2/2/Smooth.exercise/MovingAverageTask.cs) ветке [идеальный алгоритм но ска долгий]

```
Time limit exceeded
```

**Comment by KillWolfVlad** [comment]
Можно позырить лекции - лектор там код пишет

**Comment by KillWolfVlad** [comment]
* Ошибка в [master](https://github.com/KillWolfVlad/ulearn-cheats/blob/master/2/2/Smooth.exercise/MovingAverageTask.cs) ветке [хз правильно ли, но долго]

```
Time limit exceeded
```

* Ошибка в [develop-yield-avg](https://github.com/KillWolfVlad/ulearn-cheats/blob/develop-yield-avg/2/2/Smooth.exercise/MovingAverageTask.cs) ветке [идеальный алгоритм но ска долгий]

```
Time limit exceeded
```

**Comment by KonyshevArtem** [comment]
solved
