### ISSUE TITLE
Практика «Скользящий максимум»

### ISSUE THREAD

**Issue by KillWolfVlad** [KillWolfVlad/ulearn-cheats#2]
* Ошибка в [master](https://github.com/KillWolfVlad/ulearn-cheats/blob/master/2/2/Smooth.exercise/MovingMaxTask.cs) ветке [неправильный говно алгоритм]

```
Error on: NUnit test MovingMax_HiddenTests.RandomSequence 
  Expected: 15.015737906714877d +/- 9.9999999999999995E-08d
  But was:  14.215914363071761d
```

* Ошибка в [develop-yield-max](https://github.com/KillWolfVlad/ulearn-cheats/blob/develop-yield-max/2/2/Smooth.exercise/MovingMaxTask.cs) ветке [идеальный алгоритм но ска долгий]

```
Time limit exceeded
```

**Comment by KillWolfVlad** [comment]
Можно позырить лекции - лектор там код пишет

**Comment by KillWolfVlad** [comment]
Ошибка и в [master](https://github.com/KillWolfVlad/ulearn-cheats/blob/master/2/2/Smooth.exercise/MovingMaxTask.cs) ветке и в [develop-yield-max](https://github.com/KillWolfVlad/ulearn-cheats/blob/develop-yield-max/2/2/Smooth.exercise/MovingMaxTask.cs)

```
Error on: NUnit test MovingMax_HiddenTests.RandomSequence 
  Expected: 15.015737906714877d +/- 9.9999999999999995E-08d
  But was:  14.215914363071761d
```

Но тесты все проходит, плюс, я свои еще накидал

**Comment by KonyshevArtem** [comment]
solved
